config/routes.rb
Rails.application.routes.draw do

  root 'posts#splash'

  devise_for :users

  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
  end

  get 'myposts' => 'posts#myposts'
  get 'index' => 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show, :splash]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def myposts
    @posts = current_user.posts.order("created_at DESC")

  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: "Yaasss! It was posted!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notce: "Yaasss!! Updated!!"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to index_path
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :image)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title GrailsOnFeet
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %nav.navbar.navbar-inverse
    .container
      .navbar-brand= link_to "GrailsOnFeet", index_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-left
          %li= link_to "My Post!", myposts_path
          %li= link_to "Rock It!", new_post_path
          %li= link_to "Setting", edit_user_registration_path
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete

      - else
        %ul.nav.navbar-nav.navbar-left
          %li= link_to "Join", new_user_registration_path
          %li= link_to "Log In", new_user_session_path
  .container
    -flash.each do |name, msg|
      =content_tag :div, msg, class: " alert alert-info"

  = yield

app/views/posts/_form.html.haml
= simple_form_for @post, html: { multipart: true } do |f|
  - if @post.errors.any?
    #errors
      %h2
      = pluralize(@post.errors.count, "error")
      prevent this Post from saving
      %ul
        -@post.errors.full_messages.each do |msg|
          %li = msg

  .form-group
    = f.input :image, input_html: { class: 'form-control'}
  .form-group
    = f.input :title, input_html: { class: 'form-control'}
  .form-group
    = f.input :description, input_html: { class: 'form-control' }

  = f.submit :Submit, class: 'btn btn-success'

app/views/posts/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1  Edit Kick
      .panel-body
        .current_image
          %strong.center Right Now
          = image_tag @post.image.url(:medium)
        = render 'form'

app/views/posts/index.html.haml
.col-md-12
  #pics.transitions-enabled
    - @posts.each do |post|
      .box.panel.panel-default
        = link_to (image_tag post.image.url), post
        %h2= link_to post.title, post

app/views/posts/myposts.html.haml
.col-md-12
  #pics.transitions-enabled
    - @posts.each do |post|
      .box.panel.panel-default
        = link_to (image_tag post.image.url), post
        %h2= link_to post.title, post

app/views/posts/new.html.haml
.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1  Post Kick
      .panel-body
        = render 'form'

app/views/posts/show.html.haml
#pic_show.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel.heading.pic_image
        = image_tag @post.image.url
      .panel.body
        %h1= @post.title
        %p= @post.description
      .panel-footer
        .row
          .col-md-6
            %p.user
              Posted by:
              = @post.user.email

          .col-md-6
            .btn-group.pull-right
              = link_to like_post_path(@post), method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-thumbs-up
                = @post.get_upvotes.size

              - if (user_signed_in? && (current_user.id == @post.user_id))
                = link_to "Edit", edit_post_path, class: "btn btn-info"
                = link_to "Delete", post_path, method: :delete, data: { confirm: "Are you sure?!"}, class: "btn btn-danger"

app/views/posts/splash.html.haml
#bs-carousel.carousel.fade-carousel.slide{"data-interval" => "10000", "data-ride" => "carousel"}
  / Overlay
  .overlay
  / Indicators
  %ol.carousel-indicators
    %li.active{"data-slide-to" => "0", "data-target" => "#bs-carousel"}
    %li{"data-slide-to" => "1", "data-target" => "#bs-carousel"}
    %li{"data-slide-to" => "2", "data-target" => "#bs-carousel"}
  / Wrapper for slides
  .carousel-inner
    .item.slides.active
      .slide-1
      .hero
        %hgroup
          %h1 Join The Sneaker Community
          %h3 Post Your Kicks!
        / %button.btn.btn-hero.btn-lg{:role => "button", :link_to => "sneakernews.com", :target => "www.sneakernews.com", :href => "www.yahoo.com"}See all features
    .item.slides
      .slide-2
      .hero
        %hgroup
          %h1 Post It!
          %h3 What Grails Are In Your Collection?!
        / %button.btn.btn-hero.btn-lg{:role => "button"} See all features
    .item.slides
      .slide-3
      .hero
        %hgroup
          %h1 Join Now!
          %h3 Show Off Your Photography Skills!
        / %button.btn.btn-hero.btn-lg{:role => "button"} See all features